### ISSUE TITLE
update specialFunctions version

### ISSUE THREAD

**Issue by liushang0322** [jojal5/Extremes.jl#109]
could you please update SpecialFunctions' version it is too old

**Comment by houton199** [comment]
Hi @liushang0322, thanks for you issue. 

The problem comes from Mamba.jl, its compatibility requirement forces SpecialFunctions to versions 0.8, 0.9 or 0.10. 

We plan to replace Mamba.jl with a more actively maintained package but it will take some time as this will lead to major changes in Extremes.jl and we still need to determine the most suitable MCMC Julia package to replace Mamba.jl.

👀 @jojal5

**Comment by jojal5** [comment]
Hi @liushang0322, SpecialFunctions.jl is now updated.

**Comment by liushang0322** [comment]
> 你好@liushang0322, SpecialFunctions.jl 现已更新。

thank you so much
